import { PresetModel, Garment } from "./types";

export const PRESET_MODELS: PresetModel[] = [
  {
    id: "model-sophia",
    name: "Sophia",
    gender: "female",
    photoUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    heightCm: 174,
    description: "Sleek editorial posture, ideal for dresses, luxury blazers, and chic blouses.",
    topAnchor: {
      x: 32,
      y: 20,
      width: 36,
      height: 31,
    },
    bottomAnchor: {
      x: 31,
      y: 47,
      width: 38,
      height: 48,
    },
  },
  {
    id: "model-marcus",
    name: "Marcus",
    gender: "male",
    photoUrl: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&auto=format&fit=crop&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    heightCm: 185,
    description: "Broad military-style posture, best for urban hoodies, structured shirts, and denim.",
    topAnchor: {
      x: 29,
      y: 19,
      width: 42,
      height: 34,
    },
    bottomAnchor: {
      x: 28,
      y: 49,
      width: 44,
      height: 47,
    },
  },
  {
    id: "model-aria",
    name: "Aria",
    gender: "female",
    photoUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    heightCm: 168,
    description: "Cozy urban alignment, perfect for street casual apparel, outerwear list, and college jeans.",
    topAnchor: {
      x: 31,
      y: 22,
      width: 38,
      height: 29,
    },
    bottomAnchor: {
      x: 30,
      y: 48,
      width: 40,
      height: 47,
    },
  },
  {
    id: "model-rohan",
    name: "Rohan",
    gender: "male",
    photoUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    heightCm: 181,
    description: "Classic business silhouette, perfect for tuxedo style, office casuals, and sharp tailored fits.",
    topAnchor: {
      x: 25,
      y: 23,
      width: 50,
      height: 34,
    },
    bottomAnchor: {
      x: 26,
      y: 53,
      width: 48,
      height: 44,
    },
  },
];

export const GARMENTS: Garment[] = [
  // --- TOPS ---
  {
    id: "top-tee",
    name: "Classic Heavyweight Tee",
    type: "top",
    category: "casual",
    description: "Designed from premium organic cotton with a dry, tactile handle. Essential base layer.",
    colors: [
      { name: "Slate Grey", hex: "#4a5568" },
      { name: "Alabaster White", hex: "#f7fafc" },
      { name: "Deep Obsidian", hex: "#1a202c" },
      { name: "Warm Terracotta", hex: "#c53030" },
      { name: "Sage Olive", hex: "#2f855a" },
    ],
    defaultColorHex: "#4a5568",
    svgType: "tee",
    price: 39,
    brand: "AETHER Studio",
  },
  {
    id: "top-blazer",
    name: "Tailored Linen Blazer",
    type: "top",
    category: "office",
    description: "Slightly relaxed unstructured shoulder with notched lapels and lightweight breathable linen lining.",
    colors: [
      { name: "Rich Navy", hex: "#1a365d" },
      { name: "Sand Khaki", hex: "#dd6b20" },
      { name: "Warm Espresso", hex: "#4a3728" },
      { name: "Creamy Ivory", hex: "#fefcbf" },
    ],
    defaultColorHex: "#1a365d",
    svgType: "blazer",
    price: 189,
    brand: "SAVILE ROW",
  },
  {
    id: "top-hoodie",
    name: "Urban Oversized Hoodie",
    type: "top",
    category: "sporty",
    description: "Drop shoulder design, dense loopback knit cotton fleece, featuring a double-lined hood with visual weight.",
    colors: [
      { name: "Enchanted Lavender", hex: "#805ad5" },
      { name: "Sage Mint", hex: "#68d391" },
      { name: "Smoky Charcoal", hex: "#2d3748" },
      { name: "Crimson Red", hex: "#9b2c2c" },
    ],
    defaultColorHex: "#805ad5",
    svgType: "hoodie",
    price: 85,
    brand: "VYBES Athletics",
  },
  {
    id: "top-blouse",
    name: "Satin Pleated Blouse",
    type: "top",
    category: "evening",
    description: "A gorgeous flowing silhouette featuring micro-pleats with a subtle reflective metallic sheen.",
    colors: [
      { name: "Emerald Green", hex: "#22543d" },
      { name: "Amber Gold", hex: "#d69e2e" },
      { name: "Burgundy Velvet", hex: "#742a2a" },
      { name: "Champagne Silver", hex: "#edf2f7" },
    ],
    defaultColorHex: "#22543d",
    svgType: "blouse",
    price: 75,
    brand: "MAISON CHIC",
  },
  {
    id: "top-kurta",
    name: "Mandarin Collar Kurta",
    type: "top",
    category: "festive",
    description: "Premium cotton blend featuring traditional collar lines, structured side slits and subtle weaving.",
    colors: [
      { name: "Saffron Mustard", hex: "#ecc94b" },
      { name: "Royal Indigo", hex: "#2b6cb0" },
      { name: "Pure White", hex: "#ffffff" },
      { name: "Ruby Crimson", hex: "#c53030" },
    ],
    defaultColorHex: "#ecc94b",
    svgType: "kurta",
    price: 65,
    brand: "ELEGANT HERITAGE",
  },
  {
    id: "top-tuxedo",
    name: "Dapper Tuxedo Shirt",
    type: "top",
    category: "wedding",
    description: "Crisp cotton weave, bib pleated front, French cuffs, and wingtip collar, cut for perfect event contour.",
    colors: [
      { name: "Starch White", hex: "#fcfcfc" },
      { name: "Charcoal Black", hex: "#2c3539" },
      { name: "Sapphire Blue", hex: "#0f172a" },
    ],
    defaultColorHex: "#fcfcfc",
    svgType: "tuxedo_shirt",
    price: 110,
    brand: "NIGHT RUNWAY",
  },

  // --- BOTTOMS ---
  {
    id: "bottom-chinos",
    name: "Tailored Chino Trousers",
    type: "bottom",
    category: "office",
    description: "Slim-straight fit, flat-front styling in heavy stretch-cotton twill. Perfect desk-to-dinner companion.",
    colors: [
      { name: "Classic Khaki", hex: "#c0a080" },
      { name: "Steel Grey", hex: "#718096" },
      { name: "Hunter Green", hex: "#276749" },
      { name: "Dark Navy", hex: "#1a365d" },
    ],
    defaultColorHex: "#c0a080",
    svgType: "chinos",
    price: 79,
    brand: "SAVILE ROW",
  },
  {
    id: "bottom-jeans",
    name: "Premium Denim Jeans",
    type: "bottom",
    category: "casual",
    description: "Vintage stone-washed denim, straight leg tailored hem, detailed metal hardware copper stitching.",
    colors: [
      { name: "Aged Indigo", hex: "#3182ce" },
      { name: "Bleached Ice Blue", hex: "#90cdf4" },
      { name: "Soot Black", hex: "#1a202c" },
    ],
    defaultColorHex: "#3182ce",
    svgType: "jeans",
    price: 99,
    brand: "AETHER Studio",
  },
  {
    id: "bottom-skirt",
    name: "Flowing Satin Skirt",
    type: "bottom",
    category: "evening",
    description: "High-waist bias cut luxurious satin MIDI skirt, creating an effortless, gorgeous drape as you move.",
    colors: [
      { name: "Champagne Silver", hex: "#e2e8f0" },
      { name: "Forest Green", hex: "#1c4532" },
      { name: "Amber Gold", hex: "#d69e2e" },
      { name: "Royal Plum", hex: "#44337a" },
    ],
    defaultColorHex: "#e2e8f0",
    svgType: "satin_skirt",
    price: 89,
    brand: "MAISON CHIC",
  },
  {
    id: "bottom-pajama",
    name: "Ethnic Pajama Trouser",
    type: "bottom",
    category: "festive",
    description: "Comfortable drop-rise draw-string pajama with a tapered leg cuffs, tailored for cultural gatherings.",
    colors: [
      { name: "Off-White Cream", hex: "#f7fafc" },
      { name: "Desert Gold", hex: "#ecc94b" },
      { name: "Maroon Silk", hex: "#9b2c2c" },
    ],
    defaultColorHex: "#f7fafc",
    svgType: "ethnic_pajama",
    price: 45,
    brand: "ELEGANT HERITAGE",
  },
  {
    id: "bottom-pleated",
    name: "Pleated Studio Trousers",
    type: "bottom",
    category: "wedding",
    description: "Sharp double pleats at waist, high rise silhouette, heavy worsted wool blend for unmatched runway luxury.",
    colors: [
      { name: "Ink Black", hex: "#0c0f16" },
      { name: "Light Sandstone", hex: "#cbd5e0" },
      { name: "Slate Grey", hex: "#4a5568" },
    ],
    defaultColorHex: "#0c0f16",
    svgType: "pleated_pants",
    price: 135,
    brand: "NIGHT RUNWAY",
  },
];

export const LIGHTING_ENVIRONMENTS = {
  daylight: {
    name: "Natural Daylight",
    description: "Golden hour sunrays and balanced daylight shadows. High visibility.",
    bgClass: "bg-radial from-amber-50/10 via-slate-900 to-slate-950",
    filterHex: "rgba(255, 230, 180, 0.15)",
    cssFilter: "brightness(1.05) contrast(1.05) saturate(1.05) sepia(0.05)",
    shadowColor: "rgba(0, 0, 0, 0.35)",
    accentColor: "text-amber-400",
  },
  indoor: {
    name: "Boutique Indoor",
    description: "Warm glowing overhead lights. Studio spotlight conditions.",
    bgClass: "bg-radial from-orange-100/10 via-slate-900 to-slate-950",
    filterHex: "rgba(255, 210, 150, 0.2)",
    cssFilter: "brightness(0.98) contrast(1.0) saturate(1.0) sepia(0.12)",
    shadowColor: "rgba(0, 0, 0, 0.4)",
    accentColor: "text-orange-400",
  },
  evening: {
    name: "Evening Cocktail",
    description: "Purple sunset reflections and mood twilight gradients.",
    bgClass: "bg-radial from-purple-950/20 via-slate-950 to-black",
    filterHex: "rgba(180, 100, 255, 0.12)",
    cssFilter: "brightness(0.88) contrast(0.96) saturate(1.1) hue-rotate(5deg)",
    shadowColor: "rgba(0, 0, 0, 0.6)",
    accentColor: "text-purple-400",
  },
  bright: {
    name: "Bright Studio Flash",
    description: "Ultra-exposed pristine flash. Clean details, crisp silhouettes.",
    bgClass: "bg-radial from-white/10 via-slate-900 to-slate-950",
    filterHex: "rgba(255, 255, 255, 0.08)",
    cssFilter: "brightness(1.18) contrast(1.12) saturate(0.95)",
    shadowColor: "rgba(0, 0, 0, 0.25)",
    accentColor: "text-sky-400",
  },
  lowlight: {
    name: "Jazz Bar Low-Light",
    description: "Deep shadows, dim ambient teal-indigo glow. Mystique fashion.",
    bgClass: "bg-radial from-cyan-950/30 via-slate-950 to-black",
    filterHex: "rgba(100, 200, 255, 0.1)",
    cssFilter: "brightness(0.78) contrast(1.08) saturate(0.9) sepia(0.05) hue-rotate(-10deg)",
    shadowColor: "rgba(0,0,0,0.75)",
    accentColor: "text-teal-400",
  },
};
